steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/sandbox-22186/domo-pipeline-repo/domo-image/domo01:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'northamerica-northeast1-docker.pkg.dev/sandbox-22186/domo-pipeline-repo/domo-image/domo01:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'domo01'
    - '--image'
    - 'northamerica-northeast1-docker.pkg.dev/sandbox-22186/domo-pipeline-repo/domo-image/domo01:$COMMIT_SHA'
    - '--region'
    - 'northamerica-northeast1'
images:
- 'northamerica-northeast1-docker.pkg.dev/sandbox-22186/domo-pipeline-repo/domo-image/domo01:$COMMIT_SHA'